### ISSUE TITLE
wnet is not updated through all process

### ISSUE THREAD

**Issue by min9kwak** [guolz-ml/DS3L#2]
In your paper, wnet is updated by supervised loss.
However, in the code train.py, wnet is not updated through all processes.
Please check weight.grad. It is always None, and it means that there is no change of went.

(add)
I tested the code as follows:
 -remove the related parts of meta network
 -remove the related parts of w network (weight function alpha)
 -tested on CIFAR10 with 30% mismatch
 -applied Pi model as mentioned in the paper

then, I got the same result of 78%

**Comment by GanlongZhao** [comment]
Hi, I have the same question here, did you know why?
